7b_path: /home/jch/data/Qwen2-VL-7B-Instruct
2b_path: /home/jch/data/Qwen2-VL-2B-Instruct
json_path: /home/jch/data/www25/test1/test1.json
image_path: /home/jch/data/www25/test1/images/
save_path: save
id: cot_train_task1
model: cot
